### ISSUE TITLE
[Plesk] WBB extension provides extra settings which are not welcome

### ISSUE THREAD

**Issue by brentv** [yola/p-plesk#7] opened 2016-02-12 00:05 UTC
_From @olegbeznosov on January 25, 2016 10:10_

*Current behavior:*
WBB extension provides settings for SBS API (entry point, brand id, auth key), default plan, enable trial site, enable purchase, trial period, link to billing. Domains list.

*Expected behavior:*
WBB extension should not provide settings for billing and SBS API. There should be no domains list. SBS API settings should be wrapped to Plesk license and being retrieved by extension from the key. Entry point can be modified in config file if necessary. Or you have multiple entry points?

_Copied from original issue: yola/p-odin#127_

**Comment by brentv** [comment] 2016-02-12 00:05
_From @maciejhu on January 26, 2016 15:46_

We tried to get license information, but there is no details for SBS API.

<code><pre>
Array
(
    [number] => WBB.03395590.0008
    [name] => WBB.03395590.0008/ext-web-business-builder
    [active] => 1
    [filename] => /etc/sw/keys/keys/keyXXYMK1xp
    [used] => 
    [app] => Web Business Builder for Plesk
    [key-number] => WBB.03395590
    [key-version] => 0008
    [managed-by] => plesk-unified
    [product] => ext-web-business-builder
    [version] => 1.0
    [start-date] => 19990101
    [lim_date] => 20160213
    [license-server-url] => https://ka.plesk.com:5224/xmlrpc
    [license_update_date] => 20160203
    [update-ticket] => 2bdss498ubonkt3gt5-c0rts2ji0p2y1
    [multiple] => 1
    [key-body] => d0a7a555d3de4d3c1bb2ab56d85ff77c
)</pre>
</code>

**Comment by brentv** [comment] 2016-02-12 00:05
@olegbeznosov, are you seeing the same response that @maciejhu provided above?

Also, do you consider this issue to a blocker?

**Comment by brentv** [comment] 2016-02-12 00:05
_From @akhtyam on February 11, 2016 6:14_

@brentv details for SBS API will be added in additional key by Key admins on our side. Will keep you up date.

**Comment by brentv** [comment] 2016-02-12 00:05
_From @robertbray on February 11, 2016 12:9_

The SBS API authKeys are designed to be delivered to the Plesk Partner via our SBSmanager interface.  

When a new partner is setup in SBSmanager by the Odin rep this configures the necessary account details in our system and also sends an email invitation to the partner to access SBSmanager. When the partner successfully authenticates (must have single use email link and access to his mobile to retrieve a code) then he can securely download the API AuthKey, endpoint and brandid.  These values can be put into the WHMCS module so we can bond that install to the correct Brand in SBS.

In addition the partner can then configure the branding options for his account that will be used across all plesk installations.  This UI is not provided in the WHMCS module.

Finally this process also supports the sale of WBB to accounts that do not have Plesk.  For these non-Plesk WBB servers/accounts they would have no mechanism to retreive the API Keys from the Plesk Keys since Plesk would not be present.

Please let me know if you have questions on this or have any concerns.

**Comment by akugaevskiy** [comment] 2016-02-25 12:29
Duplicate of https://github.com/yola/p-plesk/issues/18

**Closed by akugaevskiy** 2016-02-25 12:29 UTC
